name: open_university_rsvpu
description: Open University for RSVPU
publish_to: 'none'
version: 1.1.1+11

environment:
  sdk: '>=2.19.4 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  provider: 6.0.5
  path_provider: ^2.0.14
  shared_preferences: 2.1.0
  http: 0.13.5
  intl: 0.18.0
  flutter_linkify: ^5.0.2
  better_player:
    git:
      url: https://github.com/tintran-dev/betterplayer.git
  easy_search_bar: ^2.4.2
  flutter_widget_from_html: ^0.8.5
  cached_network_image: ^3.2.3
  byte_converter: ^1.3.0
  package_info_plus: ^3.1.0
  animated_splash_screen: ^1.3.0
  share_plus: ^6.3.3
  onesignal_flutter: ^3.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
     - images/Loading_icon.gif
     - images/Logo.png
     - images/Front_page_screen_project_logo.png
     - images/AboutWelcomePage.png
     - images/NewsWelcomePage.png
     - images/VideoLectionsWelcomePage.png
  fonts:
    - family:  RsvpuIconClass
      fonts:
       - asset: fonts/RsvpuIconClass.ttf
